### ISSUE TITLE
hey check this out

### ISSUE THREAD

**Issue by jackmead515** [sombrerosheep/go_wasm#1]
https://github.com/jackmead515/blog/tree/master/plugins/rust-wasm-sat

didn't know how to contact ya directly 🤷  so just posted an issue. I just redesigned my physics engine into Rust WASM. It's wicked cool. Got like 20 FPS boost on it. Check it out:

https://www.speblog.org/plugin/sat-tester/

**Comment by sombrerosheep** [comment]
email me man! id love to catch up! sombrerosheep@gmail.com
